import { Routes } from "@angular/router";
import { authGuard } from "./core/auth.guard";

export const routes: Routes = [
  { path: "", loadComponent: () => import("./features/marketing/landing.page").then((m) => m.LandingPage) },
  { path: "sobre", loadComponent: () => import("./features/marketing/content.page").then((m) => m.ContentPage), data: { page: "sobre" } },
  { path: "como-funciona", loadComponent: () => import("./features/marketing/content.page").then((m) => m.ContentPage), data: { page: "como-funciona" } },
  { path: "clientes", loadComponent: () => import("./features/marketing/content.page").then((m) => m.ContentPage), data: { page: "clientes" } },
  { path: "planos", loadComponent: () => import("./features/marketing/content.page").then((m) => m.ContentPage), data: { page: "planos" } },
  { path: "contato", loadComponent: () => import("./features/marketing/content.page").then((m) => m.ContentPage), data: { page: "contato" } },
  { path: "exemplo", loadComponent: () => import("./features/marketing/example.page").then((m) => m.ExamplePage) },
  { path: "exemplo/:slug", loadComponent: () => import("./features/marketing/example-product.page").then((m) => m.ExampleProductPage) },
  { path: "termos", loadComponent: () => import("./features/marketing/legal.page").then((m) => m.LegalPage), data: { document: "terms" } },
  { path: "privacidade", loadComponent: () => import("./features/marketing/legal.page").then((m) => m.LegalPage), data: { document: "privacy" } },
  { path: "login", loadComponent: () => import("./features/auth/auth.page").then((m) => m.AuthPage), data: { mode: "login" } },
  { path: "cadastro", loadComponent: () => import("./features/auth/auth.page").then((m) => m.AuthPage), data: { mode: "register" } },
  { path: "cadastro-google", loadComponent: () => import("./features/auth/google-registration.page").then((m) => m.GoogleRegistrationPage) },
  { path: "confirmar-email", loadComponent: () => import("./features/auth/account-action.page").then((m) => m.AccountActionPage), data: { mode: "confirm" } },
  { path: "esqueci-senha", loadComponent: () => import("./features/auth/account-action.page").then((m) => m.AccountActionPage), data: { mode: "forgot" } },
  { path: "redefinir-senha", loadComponent: () => import("./features/auth/account-action.page").then((m) => m.AccountActionPage), data: { mode: "reset" } },
  { path: "p/:productId", loadComponent: () => import("./features/public-product/public-product.page").then((m) => m.PublicProductPage) },
  { path: "m/:slug", loadComponent: () => import("./features/public-menu/public-menu.page").then((m) => m.PublicMenuPage) },
  { path: "empresa/:slug", loadComponent: () => import("./features/business/public-business.page").then((m) => m.PublicBusinessPage) },
  { path: "erro/403", loadComponent: () => import("./features/errors/error.page").then((m) => m.ErrorPage), data: { code: "403" } },
  { path: "erro/500", loadComponent: () => import("./features/errors/error.page").then((m) => m.ErrorPage), data: { code: "500" } },
  { path: "indisponivel", loadComponent: () => import("./features/errors/error.page").then((m) => m.ErrorPage), data: { code: "503" } },
  {
    path: "app",
    canActivate: [authGuard],
    loadComponent: () => import("./features/dashboard/dashboard-shell.component").then((m) => m.DashboardShellComponent),
    children: [
      { path: "", pathMatch: "full", loadComponent: () => import("./features/dashboard/overview.page").then((m) => m.OverviewPage) },
      { path: "onboarding", loadComponent: () => import("./features/onboarding/onboarding.page").then((m) => m.OnboardingPage) },
      { path: "editor", loadComponent: () => import("./features/editor/editor.page").then((m) => m.EditorPage) },
      { path: "negocio", loadComponent: () => import("./features/business/business-editor.page").then((m) => m.BusinessEditorPage) },
      { path: "qr-codes", loadComponent: () => import("./features/qr/qr-center.page").then((m) => m.QrCenterPage) },
      { path: "conta", loadComponent: () => import("./features/account/account.page").then((m) => m.AccountPage) },
      { path: "**", redirectTo: "" },
    ],
  },
  { path: "**", loadComponent: () => import("./features/errors/error.page").then((m) => m.ErrorPage), data: { code: "404" } },
];
